### ISSUE TITLE
Search result links don't pop a modal

### ISSUE THREAD

**Issue by bradnoble** [cloudant-labs/cloudant-labs.github.io#1]
The wireframes included a modal on top of search results so that users can see things like related assets.

https://www.dropbox.com/s/2j827wany5va7d1/Screenshot%202015-04-21%2016.11.06.png?dl=0

The related assets will probably have to wait til the next iteration, but the modal could come now.

**Comment by glynnbird** [comment]
This one is for Christian to look at.

**Comment by ocelotpotpie** [comment]
Commtited a first pass at this here:

https://github.com/cloudant-labs/cloudant-labs.github.io/commit/a7a7bbb2a5c17ce3ad2b9b17a3affba378f85bb1
