### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by bradnoble** [cloudant-labs/cloudant-labs.github.io#14]
Slide Deck: https://speakerdeck.com/bradleyholt/cloudant-webinar-offline-enabled-apps-with-pouchdb | Webinar Page: https://cloudant.com/resources/webinars/offline-enabled-apps-with-pouchdb/ | YouTube Video: https://youtu.be/cg39JdTLSPc

**Comment by bradley-holt** [comment]
Note that you'll probably want to use the Speaker Deck link (which links to the webinar page, which then links to the video).

**Comment by glynnbird** [comment]
Added.
