### ISSUE TITLE
Search result titles should present as links -- as they were

### ISSUE THREAD

**Issue by bradnoble** [cloudant-labs/cloudant-labs.github.io#15]
Now it's just blank text, which doesn't look clickable. Also, in the future, we may offer users the option to pop the modal or go direct to the result, so we should not have the entire result block pop the modal.

**Comment by ocelotpotpie** [comment]
This is fixed in commit: https://github.com/cloudant-labs/cloudant-labs.github.io/commit/0c14299f7ce78da81bcfd84603850cf023e64bcc
