### ISSUE TITLE
Tone down the facets in the search results

### ISSUE THREAD

**Issue by bradnoble** [cloudant-labs/cloudant-labs.github.io#9]
Right now, the facets in the search results are too pronounced, and look clickable. They should present as metadata only, like this: 
![screenshot 2015-04-22 11 50 57](https://cloud.githubusercontent.com/assets/1653320/7289131/c335f724-e939-11e4-8143-1e3f3a0cb773.png)

**Comment by bradnoble** [comment]
Would also be good to truncate the body of the results so that it never exceeds 2 lines? Open to other ways to truncate, too.

**Comment by ocelotpotpie** [comment]
Truncating and facets styles updated in https://github.com/cloudant-labs/cloudant-labs.github.io/commit/c3d773b474ca3f7deefba5d0bd3ac442cb66b30c

**Comment by bradnoble** [comment]
LGTM
